insert into car (name, brand, type, year, description)
values 
('Avanza', 'Toyota', 'MPV', 2022, 'New Generation'),
('Agya', 'Toyota', 'Hatchback', 2015, ''),
('Calya', 'Toyota', 'MPV', 2016, ''),
('Veloz', 'Toyota', 'MPV', 2015, ''),
('Raize', 'Toyota', 'SUV', 2022, 'New Generation'),
('Rush', 'Toyota', 'SUV', 2020, ''),
('Hilux', 'Toyota', 'Pickup', 2022, 'New Generation'),
('Yaris', 'Toyota', 'Hatchback', 2022, 'New Generation'),
('Vios', 'Toyota', 'Sedan', 2008, ''),
('Sienta', 'Toyota', 'MPV', 2012, ''),
('Venturer', 'Toyota', 'MPV', 2022, 'New Generation'),
('HiAce', 'Toyota', 'Commercial', 2019, ''),
('Corolla Cross', 'Toyota', 'SUV', 2018, ''),
('Kijang Innova', 'Toyota', 'MPV', 2022, 'New Generation'),
('Corolla Altis', 'Toyota', 'Sedan', 2022, 'New Generation'),
('Voxy', 'Toyota', 'Commercial', 2020, ''),
('Fortuner', 'Toyota', 'SUV', 2022, 'New Generation'),
('C-HR', 'Toyota', 'SUV', 2019, ''),
('Camry', 'Toyota', 'Sedan', 2022, 'New Generation'),
('GR 86', 'Toyota', 'Sedan', 2018, ''),
('Alphard', 'Toyota', 'Commercial', 2017, ''),
('Ertiga', 'Suzuki', 'MPV', 2018, ''),
('APV Luxury', 'Suzuki', 'MPV', 2022, 'New Generation'),
('Baleno', 'Suzuki', 'Sedan', 2012, ''),
('Jimny', 'Suzuki', 'SUV', 2021, ''),
('Swift', 'Suzuki', 'Hatchback', 2022, 'New Generation'),
('Vitara Breza', 'Suzuki', 'SUV', 2021, ''),
('SX4 S-Cross', 'Suzuki', 'Hatchback', 2022, 'New Generation'),
('L300', 'Mitsubishi', 'Pickup', 2021, ''),
('Xpander', 'Mitsubishi', 'MPV', 2022, 'New Generation'),
('Triton', 'Mitsubishi', 'Pickup', 2022, 'New Generation'),
('Cross', 'Mitsubishi', 'SUV', 2020, ''),
('Outlander Sport', 'Mitsubishi', 'SUV', 2022, 'New Generation'),
('Eclipse Cross', 'Mitsubishi', 'Hatchback', 2020, ''),
('Pajero Sport', 'Mitsubishi', 'SUV', 2022, 'New Generation'),
('Outlander PHEV', 'Mitsubishi', 'SUV', 2021, ''),
('Forester', 'Subaru', 'SUV', 2022, 'New Generation'),
('Levorg', 'Subaru', 'MPV', 2022, 'New Generation'),
('Outback', 'Subaru', 'SUV', 2022, 'New Generation'),
('WRX', 'Subaru', 'Sedan', 2022, 'New Generation'),
('BRZ', 'Subaru', 'Sedan', 2021, ''),
('XV', 'Subaru', 'SUV', 2021, '');